name: nickilolk
favicon: null
layout_spectrum: 0.18918
typography_spectrum: 0.19496
title: Nicki Lolk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120c0c'
    - '#775c47'
    - '#c2ae96'
    - '#f8e7d5'
    - '#d5343c'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
